name: just_util
description: Some useful functions and extenstions for dart.
version: 1.0.3
homepage: https://github.com/JustPackages/just_util_dart
repository: https://github.com/JustPackages/just_util_dart

environment:
  sdk: ">=2.18.4 <4.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
